import { type Config } from "tailwindcss";
import animatePlugin from "tailwindcss-animate";
import tailwindLogical from "tailwindcss-logical";
import defaultTheme from "tailwindcss/defaultTheme.js";

export default {
  // mode: "jit",
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    container: {
      center: true,
      padding: "2rem",
    },
    fontFamily: {
      rubik: ["Rubik", "sans-serif"],
    },
    flex: {
      1: "1 1 0%",
      auto: "1 1 auto",
      2: "0 0 2%",
      3: "0 0 3%",
      4: "0 0 4%",
      5: "0 0 5%",
      6: "0 0 6%",
      7: "0 0 7%",
      8: "0 0 8%",
      9: "0 0 9%",
      10: "0 0 10%",
      11: "0 0 11%",
      12: "0 0 12%",
      13: "0 0 13%",
      14: "0 0 14%",
      15: "0 0 15%",
      16: "0 0 16%",
      17: "0 0 17%",
      18: "0 0 18%",
      19: "0 0 19%",
      20: "0 0 20%",
      21: "0 0 21%",
      22: "0 0 22%",
      23: "0 0 23%",
      24: "0 0 24%",
      25: "0 0 25%",
      26: "0 0 26%",
      27: "0 0 27%",
      28: "0 0 28%",
      29: "0 0 29%",
      30: "0 0 30%",
      31: "0 0 31%",
      32: "0 0 32%",
      33: "0 0 33.3%",
      34: "0 0 34%",
      35: "0 0 35%",
      36: "0 0 36%",
      37: "0 0 37%",
      38: "0 0 38%",
      39: "0 0 39%",
      40: "0 0 40%",
      41: "0 0 41%",
      42: "0 0 42%",
      43: "0 0 43%",
      44: "0 0 44%",
      45: "0 0 45%",
      46: "0 0 46%",
      47: "0 0 47%",
      48: "0 0 48%",
      49: "0 0 49%",
      50: "0 0 50%",
      60: "0 0 60%",
      61: "0 0 61%",
      62: "0 0 62%",
      63: "0 0 63%",
      64: "0 0 64%",
      65: "0 0 65%",
      66: "0 0 66.6%",
      67: "0 0 67%",
      68: "0 0 68%",
      69: "0 0 69%",
      70: "0 0 70%",
      71: "0 0 71%",
      72: "0 0 72%",
      73: "0 0 73%",
      74: "0 0 74%",
      75: "0 0 75%",
      80: "0 0 80%",
      90: "0 0 90%",
      100: "0 0 100%",
    },
    extend: {
      transitionProperty: {
        width: "width",
      },
      fontFamily: {
        sans: ["Inter", ...defaultTheme.fontFamily.sans],
        // display: ["Rubik", "sans-serif"],
        // body: ["Rubik", "sans-serif"],
      },
      boxShadow: {
        card: "var(--card-box-shadow)",
      },

      colors: {
        header: "var(--header)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "var(--background)",
        dialogBackground: "var(--dialog-background)",
        github: "var(--github)",
        "github-foreground": "var(--github-foreground)",
        google: "var(--google)",
        "google-foreground": "var(--google-foreground)",
        foreground: {
          DEFAULT: "var(--foreground)",
          destructive: "hsl(var(--foreground-destructive))",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          1: "#f5f3ff",
          2: "#ede9fe",
          3: "#ddd6fe",
          4: "#c4b5fd",
          5: "#a78bfa",
          6: "#8b5cf6",
          7: "#7c3aed",
          8: "#6d28d9",
          9: "#5b21b6",
          10: "#4c1d95",
          11: "#2e1065",
          // 12: "#2f265f",
        },
        iris: {
          1: "#fdfdff",
          2: "#f8f8ff",
          3: "#f0f1fe",
          4: "#e6e7ff",
          5: "#dadcff",
          6: "#cbcdff",
          7: "#b8baf8",
          8: "#9b9ef0",
          9: "#5b5bd6",
          10: "#5151cd",
          11: "#5753c6",
          12: "#272962",
        },
        indigo: {
          1: "#fdfdfe",
          2: "#f7f9ff",
          3: "#edf2fe",
          4: "#e1e9ff",
          5: "#d2deff",
          6: "#c1d0ff",
          7: "#abbdf9",
          8: "#8da4ef",
          9: "#3e63dd",
          10: "#3358d4",
          11: "#3a5bc7",
          12: "#1f2d5c",
        },

        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          hover: "hsl(var(--destructive-hover) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        success: {
          DEFAULT: "var(--success)",
          hover: "var(--success-hover)",
          foreground: "var(--success-foreground)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
      },
      borderRadius: {
        xl: `calc(var(--radius) + 4px)`,
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: "calc(var(--radius) - 4px)",
      },
      // backgroundImage: {
      //   "dot-pattern": "url(/images/bg-dots.svg)",
      // },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      height: {
        header: "6.5rem",
        "header-xl": "8.5rem",
      },
      width: {
        "max-lg": "980px",
        "max-xl": "1240px",
        "max-2xl": "1330px",
      },
      screens: {
        tall: {
          raw: `only screen and (max-height: 960px) and (max-width: 480px)`,
        },
        wide: {
          raw: `only screen and (max-height: 480px) and (max-width: 960px)`,
        },
        notWide: {
          raw: `only screen and (min-height: 480px) and (min-width: 767px)`,
        },

        "2xl": "1400px",
      },
      minWidth: {
        1: "1rem",
        2: "2rem",
        3: "3rem",
        4: "4rem",
        5: "5rem",
        6: "6rem",
        7: "7rem",
        32: "8rem",
        s: "15rem",
        m: "20rem",
        ml: "30rem",
        l: "40rem",
        xl: "50rem",
        "2xl": "60rem",
        "3xl": "70rem",
        "4xl": "80rem",
      },
      maxWidth: {
        ml: "30rem",
        lg: "980px",
        xl: "1240px",
        "2xl": "1330px",
      },
      minHeight: {
        1: "1rem",
        2: "2rem",
        3: "3rem",
        4: "4rem",
        5: "5rem",
        6: "6rem",
        7: "7rem",
        8: "8rem",
        9: "9rem",
        10: "10rem",
        11: "11rem",
        12: "12rem",
        13: "13rem",
        14: "14rem",
        15: "15rem",
        16: "16rem",
        17: "17rem",
        18: "18rem",
        19: "19rem",
        20: "20rem",
        32: "8rem",
        md: "40rem",
        lg: "45rem",
        xl: "50rem",
        "2xl": "60rem",
      },

      maxHeight: {
        md: "700px",
        lg: "980px",
        xl: "1240px",
        "2xl": "1330px",
      },

      // screens: {
      //   "2xs": { min: "300px" },
      //   xs: { max: "575px" }, // Mobile (iPhone 3 - iPhone XS Max).
      //   sm: { min: "576px", max: "897px" }, // Mobile (matches max: iPhone 11 Pro Max landscape @ 896px).
      //   md: { min: "898px", max: "1199px" }, // Tablet (matches max: iPad Pro @ 1112px).
      //   lg: { min: "1200px" }, // Desktop smallest.
      //   xl: { min: "1259px" }, // Desktop wide.
      //   "2xl": { min: "1359px" }, // Desktop widescreen.
      // },
      padding: {
        header: "6.5rem",
        "header-xl": "8.5rem",
      },
    },
  },
  // prefix: "tw-",
  // corePlugins: {
  //   preflight: false,
  // },
  safelist: [
    {
      pattern: /flex-|min-h-|min-w-|max-h-+/,
    },
  ],
  plugins: [
    animatePlugin,
    tailwindLogical,
    // require("@headlessui/tailwindcss")({ prefix: "ui" }),
  ],
} satisfies Config;
