export const plasmaPen = `<p data-pm-slice="1 1 []">Plasma Pen is a treatment that can only be performed by specially trained and qualified personnel who use approved equipment to shrink the skin with a sterile disposable probe. Your therapist is trained, qualified by Plasma Pen, has certification and is fully insured.</p>
<p>Before you perform the treatment, you as a patient must read and sign this consultation protocol, which gives your consent to the treatment. If your therapist considers that you are not suitable for the treatment, then your therapist will deny that your treatment is carried out.</p>
<p>Your therapist will discuss your procedure in detail, including what it will entail and the likely benefits.</p>
<p>Realistic expectations will be discussed as well as a review of possible risks. You will then receive oral and/or digital/written aftercare/information for you to retain and refer to during the subsequent healing process and it is important that you follow these instructions.</p>
<p>It is ultimately YOUR responsibility to ensure that you understand the Plasma Pen procedure and the expected results BEFORE starting treatment.</p>
<p>You must make sure that all the points below have been discussed with your therapist.&amp;nbsp;</p>
<p><strong>TERMS AND CONDITIONS FOR YOUR TREATMENT:</strong></p>
<p>&bull; You have chosen an optional cosmetic procedure that is not medically necessary</p>
<p>&bull; Treatment with Plasma Pen is an artistic process - not an exact science - and it cannot guarantee an exact result due to individual skin elasticity, individual healing process and a number of other factors.</p>
<p>&bull; Some results may be cumulative and for optimal effects to be achieved, you may therefore need to return for further treatments before your overall procedure is considered complete.</p>
<p>&bull; Depending on the treatment area, you should wait with additional treatments for about 12 weeks after the day of your first treatment. This is to allow the treated area to be given time to heal and provide the right conditions for future treatment.</p>
<p>&bull; The skin type of each client is different, and the healing process can in rare cases lead to certain discolorations of the skin. Microdermabrasion, skin rejuvenation or other relevant treatment may thus be recommended when the healing process is completed if this is the case.</p>
<p>&bull; After each treatment, slight swelling or redness may occur, which is completely normal. In some rare cases, there may be extreme swelling. Your therapist will give you appropriate advice and aftercare to reduce this eventuality.</p>
<p>&bull; During your treatment, you may experience some minor discomfort depending on the area you are treating</p>
<p>&bull; As the treatment includes small burns on the skin, you may experience the smell of charring during your treatment. This is completely normal.</p>
<p>&bull; You must follow your therapist's aftercare advice given to you after your treatment. This is especially important as it reduces the risk of infection after the procedure when you leave the clinic. You must allow the treated area to heal properly. Be gentle on the treated area as pressure and irritation may hinder the healing process and may make the treatment uneven, which requires further work. Your aftercare can make a big difference to your final result.</p>
<p>&bull; Keep in mind that all subsequent skin change procedures such as plastic surgery, implants, injectables and weight gain can change the results of the treatment</p>
<p>My signature confirms that I have read and understood the information that the form and my therapist have given me. I understand that I cannot be guaranteed any results and that the result depends on how I manage my aftercare. I understand that I will contact my doctor as soon as possible if signs of infection or other abnormal symptoms occur.</p>`;
