export const chemicalPeeling = `<p data-pm-slice="1 1 []">My partitioner has explained to me the process of peeling the skin by various acids which are called chemical peel. I understand that side effects may include, but are not limited to, increased color, decreased color, infection, pain, bleeding, swelling, scarring or damage to nearby structures, nerves, drug reactions or unforeseen complications.</p>
<p>I have received an instruction sheet as to how to care for my skin prior to and following this Procedure and agree to abide by it. I understand that proper sun protection including, but not limited to, the faithful use of broad spectrum UVA-UVB sunblock with SPF 30 is vital to proper aftercare and the reduction of risks of undesired side effects.</p>
<p>I understand that there is a possibility that this procedure will fail or be unsuccessful or need to be repeated or may require additional treatment of complications.</p>
<p>I understand my responsibility for properly fulfilling the appropriate aftercare instructions as explained by my partitioner. I hereby release and hold harmless my partitioner, facility and their suppliers from any consequences resulting from my failure to properly fulfill such aftercare instructions.</p>
<p>Since multiple treatments may be required, this consent continues for all subsequent treatments by my partitioner regardless of the time between treatments.</p>
<p>I further understand that this is a superficial type of peel that normally creates, at most, only mild redness with occasional areas of flaking or peeling skin. Depending on my skin, this may last 2-7 days.</p>
<p>I am aware that on rare occasions this peel can penetrate deeper in certain areas, causing a crusted scab to form. I understand that if this area is not treated appropriately it could become infected and possibly lead to the formation of a scar. It is my responsibility to contact my partitioner and facility if any crusted areas form or if my skin does not look and feel completely normal within one week after my peel. I acknowledge this and desire that this product be applied to my skin.</p>
<p>I am undergoing this peel in an effort to improve my skin texture and color. I understand I may achieve some improvement in my fine wrinkles as well, but no guarantee has been made to me regarding my level of improvement from this peel. My partitioner has explained to me that I may need several of these peels to achieve optimal results.</p>
<p>I understand and am willing to comply with all pre and post care instructions. This procedure has been explained to me and my questions regarding such treatment, its alternative, its complications and risks have been answered. I have been asked at this time whether I have any further questions about this procedure and I do not. I understand the procedure and accept the risks, and request that this procedure be performed on me by my partitioner, facility. The information that I have been given has been in terms clear to me and I understand the risks and complications of the treatments. My questions have been fully and completely answered for me and I have read this document and understand its contents. I hereby give my unrestricted informed consent for the procedure.</p>`;
