// This file is generated by npm run build:icons

export type IconName =
  | "app"
  | "avatar"
  | "cross-1"
  | "github-logo"
  | "pencil-1"
  | "pencil-2"
  | "plus"
  | "question-mark-circled"
  | "trash";
